

ORANGE_CAR_AGENT = "45"
ORANGE_CAR_MAC = "00:06:66:61:9B:2D"

PINK_CAR_AGENT = "10"
PINK_CAR_MAC = "00:06:66:47:0A:0A"

GREEN_CAR_AGENT = "61"
GREEN_CAR_MAC = "00:06:66:61:A9:3D"

RED_CAR_AGENT = "72"
RED_CAR_MAC = "00:06:66:61:A3:48"

MAC_TO_ID = {ORANGE_CAR_MAC: ORANGE_CAR_AGENT,
             PINK_CAR_MAC: PINK_CAR_AGENT,
             GREEN_CAR_MAC: GREEN_CAR_AGENT,
             RED_CAR_MAC: RED_CAR_AGENT}
ID_TO_MAC = {ORANGE_CAR_AGENT: ORANGE_CAR_MAC,
             PINK_CAR_AGENT: PINK_CAR_MAC,
             GREEN_CAR_AGENT: GREEN_CAR_MAC,
             RED_CAR_AGENT: RED_CAR_MAC}