

ORANGE_CAR_ID = "45"
ORANGE_CAR_MAC = "00:06:66:61:9B:2D"

PINK_CAR_ID = "10"
PINK_CAR_MAC = "00:06:66:47:0A:0A"

GREEN_CAR_ID = "61"
GREEN_CAR_MAC = "00:06:66:61:A9:3D"

RED_CAR_ID = "7"
RED_CAR_MAC = "00:06:66:61:A4:6B"

MAC_TO_ID = {ORANGE_CAR_MAC: ORANGE_CAR_ID,
             PINK_CAR_MAC: PINK_CAR_ID,
             GREEN_CAR_MAC: GREEN_CAR_ID,
             RED_CAR_MAC: RED_CAR_ID}
ID_TO_MAC = {ORANGE_CAR_ID: ORANGE_CAR_MAC,
             PINK_CAR_ID: PINK_CAR_MAC,
             GREEN_CAR_ID: GREEN_CAR_MAC,
             RED_CAR_ID: RED_CAR_MAC}